apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: php-host
  name: php-host
spec:
  type: NodePort
  ports:
  - name: "31000"
    port: 31000
    targetPort: 31000
  selector:
    io.kompose.service: php-host
